# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Tests for dependency locks and active repository workflows."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)\s+\\$")
HASH = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$")
DIRECT = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^]]+\])?==([^\s;]+)$")


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).casefold()


def _workflow_document(name: str) -> dict[str, object]:
    document = yaml.load(
        (ROOT / ".github/workflows" / name).read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    assert isinstance(document, dict)
    return document


def _workflow_steps(document: dict[str, object]) -> tuple[dict[str, object], ...]:
    jobs = document.get("jobs")
    assert isinstance(jobs, dict)
    steps: list[dict[str, object]] = []
    for job in jobs.values():
        assert isinstance(job, dict)
        raw_steps = job.get("steps", [])
        assert isinstance(raw_steps, list)
        for step in raw_steps:
            assert isinstance(step, dict)
            steps.append(step)
    return tuple(steps)


def _direct(path: Path, *, extends_runtime: bool = False) -> dict[str, str]:
    content = path.read_text(encoding="utf-8")
    result: dict[str, str] = {}
    includes: list[str] = []
    for line in content.splitlines():
        requirement = line.strip()
        if not requirement or requirement.startswith("#"):
            continue
        if requirement.startswith("-r "):
            includes.append(requirement.removeprefix("-r "))
            continue
        match = DIRECT.fullmatch(requirement)
        assert match is not None, requirement
        name = _normalize(match.group(1))
        assert name not in result
        result[name] = match.group(2)
    assert result
    assert includes == (["requirements.in"] if extends_runtime else [])
    if extends_runtime:
        runtime = _direct(path.parent / "requirements.in")
        assert not set(runtime) & set(result)
        return runtime | result
    return result


def _lock(path: Path, *, source: str) -> tuple[dict[str, str], dict[str, set[str]]]:
    content = path.read_text(encoding="utf-8")
    assert "This file is autogenerated by pip-compile" in content
    assert "--allow-unsafe" in content
    assert "--generate-hashes" in content
    assert "--no-emit-find-links" in content
    assert "--strip-extras" in content
    header = "\n".join(content.splitlines()[:8])
    assert source in header
    assert "--extra=" not in header
    assert "pyproject.toml" not in header

    pins: dict[str, str] = {}
    package_hashes: dict[str, set[str]] = {}
    current: str | None = None

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line[:1].isspace():
            match = HASH.fullmatch(stripped)
            assert match is not None and current is not None, (path, line)
            assert match.group(1) not in package_hashes[current], (path, line)
            package_hashes[current].add(match.group(1))
            continue
        match = PIN.fullmatch(line)
        assert match is not None, (path, line)
        current = _normalize(match.group(1))
        assert current not in pins, (path, current)
        pins[current] = match.group(2)
        package_hashes[current] = set()
    assert pins and all(package_hashes.values())
    return pins, package_hashes


def test_hash_locks_match_exact_dependency_inputs_and_published_wheel() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    assert project["project"]["dynamic"] == ["dependencies"]
    assert "dependencies" not in project["project"]
    assert "optional-dependencies" not in project["project"]
    assert project["tool"]["setuptools"]["dynamic"]["dependencies"] == {
        "file": ["requirements.in"]
    }
    assert not (ROOT / "tools/lint/pyproject.toml").exists()
    expected_inputs = {
        "requirements.in",
        "requirements-dev.in",
        "requirements-docs.in",
        "requirements-lint.in",
        "requirements-standalone.in",
    }
    assert {path.name for path in ROOT.glob("requirements*.in")} == expected_inputs

    runtime_direct = _direct(ROOT / "requirements.in")
    development_direct = _direct(ROOT / "requirements-dev.in", extends_runtime=True)
    docs_direct = _direct(ROOT / "requirements-docs.in", extends_runtime=True)
    standalone_direct = _direct(
        ROOT / "requirements-standalone.in", extends_runtime=True
    )
    lint_direct = _direct(ROOT / "requirements-lint.in")

    runtime, runtime_hashes = _lock(ROOT / "requirements.txt", source="requirements.in")
    development, development_hashes = _lock(
        ROOT / "requirements-dev.txt", source="requirements-dev.in"
    )
    lint, _lint_hashes = _lock(
        ROOT / "requirements-lint.txt", source="requirements-lint.in"
    )
    standalone, standalone_hashes = _lock(
        ROOT / "requirements-standalone.txt", source="requirements-standalone.in"
    )
    docs, docs_hashes = _lock(
        ROOT / "requirements-docs.txt", source="requirements-docs.in"
    )

    assert runtime_direct.items() <= runtime.items()
    assert development_direct.items() <= development.items()
    assert lint == lint_direct
    assert standalone_direct.items() <= standalone.items()
    assert docs_direct.items() <= docs.items()
    wrapper_version = runtime_direct["ssh-wrapper"]
    assert runtime["ssh-wrapper"] == wrapper_version
    assert development["ssh-wrapper"] == wrapper_version
    assert standalone["ssh-wrapper"] == wrapper_version
    assert docs["ssh-wrapper"] == wrapper_version
    wrapper_hashes = runtime_hashes["ssh-wrapper"]
    assert development_hashes["ssh-wrapper"] == wrapper_hashes
    assert standalone_hashes["ssh-wrapper"] == wrapper_hashes
    assert docs_hashes["ssh-wrapper"] == wrapper_hashes


def test_python_313_and_314_are_both_enforced_by_metadata_and_ci() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    workflow = _workflow_document("ci.yml")
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    compatibility = (ROOT / "containers/compatibility/Containerfile").read_text(
        encoding="utf-8"
    )
    ruff = (ROOT / "ruff.toml").read_text(encoding="utf-8")

    assert project["project"]["requires-python"] == ">=3.13,<3.15"
    assert project["tool"]["mypy"]["python_version"] == "3.13"
    setup_versions = [
        step["with"]["python-version"]
        for step in _workflow_steps(workflow)
        if isinstance(step.get("uses"), str)
        and str(step["uses"]).startswith("actions/setup-python@")
        and isinstance(step.get("with"), dict)
    ]
    assert setup_versions and set(setup_versions) == {"3.14"}
    assert re.search(r"^ci:\s+check audit$", makefile, re.MULTILINE)
    assert "compatibility-python" in makefile
    assert "python313" in makefile
    assert "python:3.13-slim@sha256:" in compatibility
    assert 'target-version = "py313"' in ruff


def test_make_installs_the_hash_locked_published_wheel() -> None:
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")

    assert makefile.count("--require-hashes") >= 4
    assert makefile.count("--only-binary=:all:") >= 4
    assert "--find-links" not in makefile
    assert "--rebuild" in makefile
    assert "import importlib.metadata, pathlib, remote_ssh_mcp, ssh_wrapper" in makefile
    assert 'pathlib.Path(".version")' in makefile
    assert 'importlib.metadata.version("remote-ssh-mcp") == expected' in makefile
    assert 'importlib.metadata.version("remote-ssh-mcp") == "0.2.0"' not in makefile
    assert re.search(r"^package:\s+dev-venv$", makefile, re.MULTILINE)
    assert "-m build --no-isolation --wheel --sdist" in makefile
    assert 'entry_point="$$install_root/bin/remote-ssh-mcp"' in makefile
    assert "from remote_ssh_mcp.config import runtime_repository_root" in makefile
    assert '"$$entry_point" --connect-timeout 0' in makefile
    assert "connect timeout must be between" in makefile
    assert re.search(r"^ci:\s+check audit$", makefile, re.MULTILINE)
    assert re.search(r"^standalone:\s+standalone-venv$", makefile, re.MULTILINE)
    assert re.search(r"^smoke-standalone:\s+standalone$", makefile, re.MULTILINE)
    assert "tools/verify_standalone.py" in makefile

    build_standalone = (ROOT / "tools/build_standalone.py").read_text(encoding="utf-8")
    standalone_lock = (ROOT / "requirements-standalone.txt").read_text(encoding="utf-8")
    assert '"--collect-submodules",\n        "mcp"' not in build_standalone
    assert "typer==" not in standalone_lock


def test_active_workflows_are_complete_pinned_and_root_native() -> None:
    workflow_directory = ROOT / ".github/workflows"
    workflows = tuple(sorted(workflow_directory.glob("*.yml")))
    assert workflows
    external_actions: list[str] = []
    for path in workflows:
        document = _workflow_document(path.name)
        assert document.get("permissions") == {"contents": "read"}
        for step in _workflow_steps(document):
            action = step.get("uses")
            if not isinstance(action, str) or action.startswith("./"):
                continue
            external_actions.append(action)
            assert re.fullmatch(r"[^@\s]+@[0-9a-f]{40}", action)
            if action.startswith("actions/checkout@"):
                options = step.get("with")
                assert isinstance(options, dict)
                assert options.get("persist-credentials") == "false"
                assert "repository" not in options
    assert external_actions


def test_ci_distinguishes_published_maintenance_from_unpublished_stasis() -> None:
    workflow = _workflow_document("ci.yml")
    triggers = workflow.get("on")
    jobs = workflow.get("jobs")
    assert isinstance(triggers, dict) and isinstance(jobs, dict)
    workflow_call = triggers.get("workflow_call")
    assert isinstance(workflow_call, dict)
    inputs = workflow_call.get("inputs")
    assert isinstance(inputs, dict)
    base_ref = inputs.get("base_ref")
    assert isinstance(base_ref, dict) and base_ref.get("default") == ""

    version = jobs.get("version")
    assert isinstance(version, dict)
    assert "permissions" not in version
    steps = version.get("steps")
    assert isinstance(steps, list)
    baseline = next(
        step
        for step in steps
        if isinstance(step, dict) and step.get("id") == "baseline"
    )
    baseline_options = baseline.get("with")
    assert isinstance(baseline_options, dict)
    baseline_script = baseline_options.get("script")
    assert isinstance(baseline_script, str)
    assert "github.rest.repos.getReleaseByTag" in baseline_script
    assert (
        "publishedCurrent = currentRelease.data.tag_name === current" in baseline_script
    )
    assert 'core.setOutput("published_current_version"' in baseline_script
    assert 'core.setOutput("unpublished_base_version"' in baseline_script

    comparison = next(
        step.get("run")
        for step in steps
        if isinstance(step, dict) and isinstance(step.get("run"), str)
    )
    assert 'if [[ "$current_version" != "$BASE_VERSION" ]]' in comparison
    assert 'elif [[ "$PUBLISHED_CURRENT_VERSION" != "true" ]]' in comparison
    assert "--unpublished-base-version $UNPUBLISHED_BASE_VERSION" in comparison


def test_pr_body_is_the_only_pull_request_target_write_boundary() -> None:
    workflow_directory = ROOT / ".github/workflows"
    documents = {
        path.name: _workflow_document(path.name)
        for path in sorted(workflow_directory.glob("*.yml"))
    }
    target_workflows = [
        document
        for document in documents.values()
        if "pull_request_target" in document.get("on", {})
    ]
    assert len(target_workflows) == 1
    workflow = target_workflows[0]
    trigger = workflow["on"]["pull_request_target"]
    assert trigger["branches"] == ["main"]
    assert trigger["paths"] == ["CHANGELOG.md"]

    write_boundaries: list[dict[str, object]] = []
    for document in documents.values():
        jobs = document.get("jobs")
        assert isinstance(jobs, dict)
        for job in jobs.values():
            assert isinstance(job, dict)
            permissions = job.get("permissions", {})
            assert isinstance(permissions, dict)
            if permissions.get("pull-requests") == "write":
                write_boundaries.append(job)
    assert len(write_boundaries) == 1
    assert write_boundaries[0] in workflow["jobs"].values()

    for step in _workflow_steps(workflow):
        action = step.get("uses")
        if not isinstance(action, str) or not action.startswith("actions/checkout@"):
            continue
        options = step.get("with")
        assert isinstance(options, dict)
        assert "ref" not in options


def test_pages_builds_prs_but_deploys_only_trusted_main() -> None:
    workflow = _workflow_document("pages.yml")
    triggers = workflow["on"]
    permissions = workflow["permissions"]
    jobs = workflow["jobs"]
    assert isinstance(triggers, dict)
    assert isinstance(permissions, dict)
    assert isinstance(jobs, dict)

    assert set(triggers) == {"pull_request", "push", "workflow_dispatch"}
    assert triggers["pull_request"]["branches"] == ["main"]
    assert triggers["push"]["branches"] == ["main"]
    assert permissions == {"contents": "read"}

    build = jobs["build"]
    deploy = jobs["deploy"]
    assert isinstance(build, dict) and isinstance(deploy, dict)
    assert "permissions" not in build
    assert deploy["needs"] == "build"
    assert deploy["permissions"] == {"pages": "write", "id-token": "write"}
    deployment_condition = deploy["if"]
    assert isinstance(deployment_condition, str)
    assert "github.event_name == 'push'" in deployment_condition
    assert "github.ref == 'refs/heads/main'" in deployment_condition

    build_steps = build["steps"]
    deploy_steps = deploy["steps"]
    assert isinstance(build_steps, list) and isinstance(deploy_steps, list)
    build_actions = {step.get("uses", "") for step in build_steps}
    deploy_actions = {step.get("uses", "") for step in deploy_steps}
    assert any(
        action.startswith("actions/upload-pages-artifact@") for action in build_actions
    )
    assert any(action.startswith("actions/deploy-pages@") for action in deploy_actions)


def test_governance_files_are_repository_local() -> None:
    assert (
        (ROOT / ".github/CODEOWNERS")
        .read_text(encoding="utf-8")
        .endswith("* @kogeler\n")
    )
    dependabot = yaml.load(
        (ROOT / ".github/dependabot.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    assert isinstance(dependabot, dict)
    updates = dependabot.get("updates")
    assert isinstance(updates, list)
    ecosystems = {
        update["package-ecosystem"]: update
        for update in updates
        if isinstance(update, dict) and "package-ecosystem" in update
    }
    assert set(ecosystems) == {"pip", "github-actions"}
    for update in ecosystems.values():
        assert update.get("directory") == "/"
    python_updates = ecosystems["pip"]
    groups = python_updates.get("groups")
    assert isinstance(groups, dict) and len(groups) == 1
    group = next(iter(groups.values()))
    assert isinstance(group, dict)
    assert group.get("patterns") == ["*"]
    assert "ignore" not in python_updates
    assert python_updates.get("exclude-paths") == ["pyproject.toml"]
    resolver_versions: set[tuple[str, str]] = set()
    for containerfile in (
        ROOT / "containers/toolbox/Containerfile",
        ROOT / "containers/compatibility/Containerfile",
    ):
        content = containerfile.read_text(encoding="utf-8")
        pip_match = re.search(r"^[ ]*pip==([^ \\\n]+)", content, re.MULTILINE)
        tools_match = re.search(r"^[ ]*pip-tools==([^ \\\n]+)", content, re.MULTILINE)
        assert pip_match is not None and tools_match is not None
        resolver_versions.add((pip_match.group(1), tools_match.group(1)))
    assert resolver_versions == {("26.1.1", "7.5.3")}
    assert (ROOT / ".github/dependency-audit-exceptions.json").is_file()
    assert (ROOT / ".github/dependency-review-config.yml").is_file()
    ignored = (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    assert "/.artifacts/" in ignored
    assert "/.dependencies/" not in ignored


def test_ci_checkouts_never_replace_the_published_dependency() -> None:
    workflow = _workflow_document("ci.yml")
    checkout_steps = [
        step
        for step in _workflow_steps(workflow)
        if isinstance(step.get("uses"), str)
        and str(step["uses"]).startswith("actions/checkout@")
    ]
    assert checkout_steps
    for step in checkout_steps:
        options = step.get("with")
        assert isinstance(options, dict)
        assert "repository" not in options
        assert "path" not in options


def test_release_publishes_only_the_two_gated_executables_and_checksums() -> None:
    """Release reuses CI bytes and verifies a closed standalone inventory."""
    workflow = _workflow_document("release.yml")
    triggers = workflow.get("on")
    assert isinstance(triggers, dict)
    push = triggers.get("push")
    assert isinstance(push, dict)
    assert push.get("branches") == ["main"]
    assert "paths" not in push
    jobs = workflow.get("jobs")
    assert isinstance(jobs, dict)

    release_state = jobs.get("release-state")
    assert isinstance(release_state, dict)
    state_steps = release_state.get("steps")
    assert isinstance(state_steps, list)
    state_check = next(
        step
        for step in state_steps
        if isinstance(step, dict) and step.get("id") == "check"
    )
    state_options = state_check.get("with")
    assert isinstance(state_options, dict)
    state_script = state_options.get("script")
    assert isinstance(state_script, str)
    assert "const readFile = async (path, ref = context.sha)" in state_script
    assert "const published = Boolean(existing && !existing.draft)" in state_script
    assert (
        "const releaseCommit = published ? tag.data.object.sha : context.sha"
        in state_script
    )
    assert 'await readFile(".version", releaseCommit)' in state_script
    assert 'await readFile("CHANGELOG.md", releaseCommit)' in state_script
    assert "existing.target_commitish !== releaseCommit" in state_script
    assert 'core.setOutput("release_required", "false")' in state_script

    reusable_ci = [
        job
        for job in jobs.values()
        if isinstance(job, dict) and job.get("uses") == "./.github/workflows/ci.yml"
    ]
    assert len(reusable_ci) == 1
    assert reusable_ci[0].get("needs") == "release-state"
    assert reusable_ci[0].get("if") == (
        "needs.release-state.outputs.release_required == 'true'"
    )
    inputs = reusable_ci[0].get("with")
    assert isinstance(inputs, dict)
    assert inputs.get("base_ref") == "${{ github.event.before }}"
    assert inputs.get("upload_release_artifacts") == "true"

    publishing_jobs = [
        job
        for job in jobs.values()
        if isinstance(job, dict)
        and isinstance(job.get("permissions"), dict)
        and job["permissions"].get("contents") == "write"
    ]
    assert len(publishing_jobs) == 1
    assert publishing_jobs[0].get("needs") == ["release-state", "ci"]
    assert publishing_jobs[0].get("if") == (
        "needs.release-state.outputs.release_required == 'true'"
    )
    downloads = [
        step
        for step in publishing_jobs[0].get("steps", [])
        if isinstance(step, dict)
        and isinstance(step.get("uses"), str)
        and str(step["uses"]).startswith("actions/download-artifact@")
    ]
    artifact_names = {
        step["with"]["name"]
        for step in downloads
        if isinstance(step.get("with"), dict) and "name" in step["with"]
    }
    assert artifact_names == {"standalone-amd64", "standalone-arm64"}


def test_live_target_uses_one_bounded_low_id_namespace() -> None:
    makefile = (ROOT / "make/container.mk").read_text(encoding="utf-8")
    process = (ROOT / "tests/live_support/process.py").read_text(encoding="utf-8")
    installer = (ROOT / "containers/live-target/install-base.sh").read_text(
        encoding="utf-8"
    )
    target_policy = makefile.split("LIVE_TARGET_CONFINE =", maxsplit=1)[1].split(
        "# A full", maxsplit=1
    )[0]

    assert target_policy.count("--userns=auto:size=2048") == 1
    assert 'LIVE_USER_NAMESPACE = "--userns=auto:size=2048"' in process
    assert "groupadd --system sshd" in installer
    assert "usermod --gid sshd sshd" in installer
    assert "((sshd_gid < 2048))" in installer


def test_launcher_uses_one_isolated_installed_module_boundary() -> None:
    launcher = (ROOT / "remote-ssh-mcp").read_text(encoding="utf-8")
    module_entry = (ROOT / "remote_ssh_mcp/__main__.py").read_text(encoding="utf-8")
    config = (ROOT / "remote_ssh_mcp/config.py").read_text(encoding="utf-8")

    assert 'exec "${venv_python}" -I -m remote_ssh_mcp "$@"' in launcher
    assert "main()" in module_entry
    assert "Path(__file__)" not in module_entry
    assert "def runtime_repository_root()" in config
    assert 'root / ".version"' in config
    assert "project_version != __version__" in config
    assert "Path(__file__).resolve().parents" not in config
